/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AnonymousTransportInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "carrierRoutes"
      | "deactivateRoute"
      | "getCarrierRoutes"
      | "getRequestStatus"
      | "getRouteInfo"
      | "getScheduleInfo"
      | "getUserRequests"
      | "matchRequest"
      | "optimizeSchedule"
      | "owner"
      | "reactivateRoute"
      | "registerRoute"
      | "requestCounter"
      | "requests"
      | "routeCounter"
      | "routes"
      | "schedules"
      | "submitTransportRequest"
      | "userRequests"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RequestSubmitted"
      | "RouteRegistered"
      | "ScheduleOptimized"
      | "TransportMatched"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "carrierRoutes",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateRoute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCarrierRoutes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRouteInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getScheduleInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRequests",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "matchRequest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "optimizeSchedule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reactivateRoute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerRoute",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "requestCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "routeCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "routes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "schedules",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitTransportRequest",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "userRequests",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "carrierRoutes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateRoute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCarrierRoutes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequestStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRouteInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getScheduleInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optimizeSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivateRoute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerRoute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "routeCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "routes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "schedules", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitTransportRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userRequests",
    data: BytesLike
  ): Result;
}

export namespace RequestSubmittedEvent {
  export type InputTuple = [requestId: BigNumberish, requester: AddressLike];
  export type OutputTuple = [requestId: bigint, requester: string];
  export interface OutputObject {
    requestId: bigint;
    requester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouteRegisteredEvent {
  export type InputTuple = [routeId: BigNumberish, carrier: AddressLike];
  export type OutputTuple = [routeId: bigint, carrier: string];
  export interface OutputObject {
    routeId: bigint;
    carrier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScheduleOptimizedEvent {
  export type InputTuple = [routeId: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [routeId: bigint, timestamp: bigint];
  export interface OutputObject {
    routeId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransportMatchedEvent {
  export type InputTuple = [requestId: BigNumberish, routeId: BigNumberish];
  export type OutputTuple = [requestId: bigint, routeId: bigint];
  export interface OutputObject {
    requestId: bigint;
    routeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AnonymousTransport extends BaseContract {
  connect(runner?: ContractRunner | null): AnonymousTransport;
  waitForDeployment(): Promise<this>;

  interface: AnonymousTransportInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  carrierRoutes: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  deactivateRoute: TypedContractMethod<
    [_routeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCarrierRoutes: TypedContractMethod<
    [_carrier: AddressLike],
    [bigint[]],
    "view"
  >;

  getRequestStatus: TypedContractMethod<
    [_requestId: BigNumberish],
    [
      [boolean, string, bigint, bigint] & {
        isMatched: boolean;
        requester: string;
        assignedRoute: bigint;
        requestTime: bigint;
      }
    ],
    "view"
  >;

  getRouteInfo: TypedContractMethod<
    [_routeId: BigNumberish],
    [
      [boolean, string, bigint] & {
        isActive: boolean;
        carrier: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getScheduleInfo: TypedContractMethod<
    [_routeId: BigNumberish],
    [
      [boolean, bigint, bigint] & {
        isOptimized: boolean;
        scheduleTime: bigint;
        requestCount: bigint;
      }
    ],
    "view"
  >;

  getUserRequests: TypedContractMethod<
    [_user: AddressLike],
    [bigint[]],
    "view"
  >;

  matchRequest: TypedContractMethod<
    [_requestId: BigNumberish, _routeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  optimizeSchedule: TypedContractMethod<
    [_routeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  reactivateRoute: TypedContractMethod<
    [_routeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerRoute: TypedContractMethod<
    [
      _startX: BigNumberish,
      _startY: BigNumberish,
      _endX: BigNumberish,
      _endY: BigNumberish,
      _capacity: BigNumberish,
      _priority: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  requestCounter: TypedContractMethod<[], [bigint], "view">;

  requests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        boolean,
        string,
        bigint,
        bigint
      ] & {
        pickupX: string;
        pickupY: string;
        dropX: string;
        dropY: string;
        weight: string;
        urgency: string;
        maxCost: string;
        isMatched: boolean;
        requester: string;
        assignedRoute: bigint;
        requestTime: bigint;
      }
    ],
    "view"
  >;

  routeCounter: TypedContractMethod<[], [bigint], "view">;

  routes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        boolean,
        string,
        bigint
      ] & {
        startX: string;
        startY: string;
        endX: string;
        endY: string;
        capacity: string;
        priority: string;
        isActive: boolean;
        carrier: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  schedules: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, boolean, bigint] & {
        routeId: bigint;
        totalLoad: string;
        efficiency: string;
        isOptimized: boolean;
        scheduleTime: bigint;
      }
    ],
    "view"
  >;

  submitTransportRequest: TypedContractMethod<
    [
      _pickupX: BigNumberish,
      _pickupY: BigNumberish,
      _dropX: BigNumberish,
      _dropY: BigNumberish,
      _weight: BigNumberish,
      _urgency: BigNumberish,
      _maxCost: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  userRequests: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "carrierRoutes"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateRoute"
  ): TypedContractMethod<[_routeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCarrierRoutes"
  ): TypedContractMethod<[_carrier: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRequestStatus"
  ): TypedContractMethod<
    [_requestId: BigNumberish],
    [
      [boolean, string, bigint, bigint] & {
        isMatched: boolean;
        requester: string;
        assignedRoute: bigint;
        requestTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRouteInfo"
  ): TypedContractMethod<
    [_routeId: BigNumberish],
    [
      [boolean, string, bigint] & {
        isActive: boolean;
        carrier: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getScheduleInfo"
  ): TypedContractMethod<
    [_routeId: BigNumberish],
    [
      [boolean, bigint, bigint] & {
        isOptimized: boolean;
        scheduleTime: bigint;
        requestCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserRequests"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "matchRequest"
  ): TypedContractMethod<
    [_requestId: BigNumberish, _routeId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "optimizeSchedule"
  ): TypedContractMethod<[_routeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reactivateRoute"
  ): TypedContractMethod<[_routeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerRoute"
  ): TypedContractMethod<
    [
      _startX: BigNumberish,
      _startY: BigNumberish,
      _endX: BigNumberish,
      _endY: BigNumberish,
      _capacity: BigNumberish,
      _priority: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        boolean,
        string,
        bigint,
        bigint
      ] & {
        pickupX: string;
        pickupY: string;
        dropX: string;
        dropY: string;
        weight: string;
        urgency: string;
        maxCost: string;
        isMatched: boolean;
        requester: string;
        assignedRoute: bigint;
        requestTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "routeCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "routes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        boolean,
        string,
        bigint
      ] & {
        startX: string;
        startY: string;
        endX: string;
        endY: string;
        capacity: string;
        priority: string;
        isActive: boolean;
        carrier: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "schedules"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, boolean, bigint] & {
        routeId: bigint;
        totalLoad: string;
        efficiency: string;
        isOptimized: boolean;
        scheduleTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitTransportRequest"
  ): TypedContractMethod<
    [
      _pickupX: BigNumberish,
      _pickupY: BigNumberish,
      _dropX: BigNumberish,
      _dropY: BigNumberish,
      _weight: BigNumberish,
      _urgency: BigNumberish,
      _maxCost: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userRequests"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "RequestSubmitted"
  ): TypedContractEvent<
    RequestSubmittedEvent.InputTuple,
    RequestSubmittedEvent.OutputTuple,
    RequestSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "RouteRegistered"
  ): TypedContractEvent<
    RouteRegisteredEvent.InputTuple,
    RouteRegisteredEvent.OutputTuple,
    RouteRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ScheduleOptimized"
  ): TypedContractEvent<
    ScheduleOptimizedEvent.InputTuple,
    ScheduleOptimizedEvent.OutputTuple,
    ScheduleOptimizedEvent.OutputObject
  >;
  getEvent(
    key: "TransportMatched"
  ): TypedContractEvent<
    TransportMatchedEvent.InputTuple,
    TransportMatchedEvent.OutputTuple,
    TransportMatchedEvent.OutputObject
  >;

  filters: {
    "RequestSubmitted(uint32,address)": TypedContractEvent<
      RequestSubmittedEvent.InputTuple,
      RequestSubmittedEvent.OutputTuple,
      RequestSubmittedEvent.OutputObject
    >;
    RequestSubmitted: TypedContractEvent<
      RequestSubmittedEvent.InputTuple,
      RequestSubmittedEvent.OutputTuple,
      RequestSubmittedEvent.OutputObject
    >;

    "RouteRegistered(uint32,address)": TypedContractEvent<
      RouteRegisteredEvent.InputTuple,
      RouteRegisteredEvent.OutputTuple,
      RouteRegisteredEvent.OutputObject
    >;
    RouteRegistered: TypedContractEvent<
      RouteRegisteredEvent.InputTuple,
      RouteRegisteredEvent.OutputTuple,
      RouteRegisteredEvent.OutputObject
    >;

    "ScheduleOptimized(uint32,uint256)": TypedContractEvent<
      ScheduleOptimizedEvent.InputTuple,
      ScheduleOptimizedEvent.OutputTuple,
      ScheduleOptimizedEvent.OutputObject
    >;
    ScheduleOptimized: TypedContractEvent<
      ScheduleOptimizedEvent.InputTuple,
      ScheduleOptimizedEvent.OutputTuple,
      ScheduleOptimizedEvent.OutputObject
    >;

    "TransportMatched(uint32,uint32)": TypedContractEvent<
      TransportMatchedEvent.InputTuple,
      TransportMatchedEvent.OutputTuple,
      TransportMatchedEvent.OutputObject
    >;
    TransportMatched: TypedContractEvent<
      TransportMatchedEvent.InputTuple,
      TransportMatchedEvent.OutputTuple,
      TransportMatchedEvent.OutputObject
    >;
  };
}
